root: true
env:
  browser: true
  commonjs: true
  es2021: true
  node: true
extends:
  - standard-with-typescript
  - plugin:react/recommended
  - prettier
parserOptions:
  ecmaVersion: latest
  project:
    - packages/*/tsconfig.json
plugins:
  - react
ignorePatterns:
  - dist
rules: {}
