root: true
env:
  browser: true
  commonjs: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended-type-checked
  - plugin:react/recommended
settings:
  react:
    version: detect
parserOptions:
  ecmaVersion: latest
  project:
    - packages/*/tsconfig.json
ignorePatterns:
  - dist
  - "*.mjs"
rules:
  "@typescript-eslint/semi": "warn"
  "@typescript-eslint/no-explicit-any": "off"
  "@typescript-eslint/no-unused-vars": ["warn", { "argsIgnorePattern": "^_" }]
  "@typescript-eslint/unbound-method": ["error", { "ignoreStatic": true }]
  "@typescript-eslint/no-non-null-assertion": "off"
  "@typescript-eslint/require-await": "off"
  "react/react-in-jsx-scope": "off"
  "curly": "warn"
  "eqeqeq": "warn"
  "no-throw-literal": "warn"

