compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

plugins:
  # workaround because vsce is not yet compatible with yarn v2+
  # https://github.com/microsoft/vscode-vsce/issues/517
  # https://github.com/arendjr/yarn-plugin-list
  - path: .yarn/plugins/plugin-list.cjs
    spec: "https://github.com/arendjr/yarn-plugin-list/releases/latest/download/yarn-plugin-list.js"

yarnPath: .yarn/releases/yarn-4.1.1.cjs
