nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

    # workaround because vsce is not yet compatible with yarn v2+
    # https://github.com/microsoft/vscode-vsce/issues/517
    # https://github.com/arendjr/yarn-plugin-list
  - path: .yarn/plugins/plugin-list.cjs
    spec: "https://github.com/arendjr/yarn-plugin-list/releases/latest/download/yarn-plugin-list.js"

yarnPath: .yarn/releases/yarn-3.6.1.cjs
